services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:v6.13.0_10.1.4-${NETWORK}
    logging:
      driver: json-file
      options:
        max-size: 400k
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
      - ${CARDANO_PORT:-3000}:3000
    volumes:
      - node-db:/db
      - node-ipc:/ipc
    restart: on-failure

  rapidoc-ogmios:
    build:
      context: .
      target: rapidoc-ogmios
    ports:
      - ${RAPIDOC_OGMIOS_PORT:-2500}:2500
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"

volumes:
  node-db:
  node-ipc:
